### TO WORK WITH "APP.HTTP" FILE YOU HAVE TO INSTALL "REST CLIENT" EXTENSION TO YOUR "VS CODE"  ###

###
POST https://u84g6plpn8.execute-api.us-west-1.amazonaws.com/episodes/search
content-type: application/json
Authorization: bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImI3MGxqUlo5ak5UWEIwWmhFVlliUyJ9.eyJuaWNrbmFtZSI6InNpcnI1MDUwIiwibmFtZSI6IlJhaHVsIiwicGljdHVyZSI6Imh0dHBzOi8vcy5ncmF2YXRhci5jb20vYXZhdGFyLzc5NzY5MjQ3Mjg3NzgwMjdjMTc1OGEwZWE5MDEwZTA4P3M9NDgwJnI9cGcmZD1odHRwcyUzQSUyRiUyRmNkbi5hdXRoMC5jb20lMkZhdmF0YXJzJTJGcmEucG5nIiwidXBkYXRlZF9hdCI6IjIwMjAtMDktMzBUMDk6NTI6MTYuMzY5WiIsImVtYWlsIjoic2lycjUwNTBAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsImlzcyI6Imh0dHBzOi8vaG9wZWZtLnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJhdXRoMHw1ZjRkZjExN2ZhMzY3YTAwNjgwYWZjZWYiLCJhdWQiOiJIQnF0QUJFTEZsME1Iazk5UWlFTXhYVnRXbldtNXI1NyIsImlhdCI6MTYwMTQ1OTUzNiwiZXhwIjoxNjA1MDU5NTM2fQ.H4lf39yuCBxM_yxlP8d_3jseZ27fbS3766RLr-LXGcGMNNBW2hSVZGmAm_1V4Uu4Nh5Id8AyyEC4wBTHLnzTZssf6RkLJUEMZtv3leUOsQV2sqD6NQ5LAtUnViRtvY9TJtZMfKcCfz8ApQlq7_8bOgGTbYjpfMBCosNU7-gN1r_NBH91InRxYw6g_OnoouECptEeZXwsU4jPFFgYYdqiRJJeCgiCoqT9Y2xb4T3Cm0L0mkgxi7aRv7jThFp9_OFlBiupb4cRCrmSIp_ipR7dYKZvOpcZ3GgjAG34CSwAhHZ-W2BPDa8ldI9iNs3pdo6KThJBHzcf3xJObPJ9a-xl7g

###
GET https://u84g6plpn8.execute-api.us-west-1.amazonaws.com/categories/all
Authorization: bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImI3MGxqUlo5ak5UWEIwWmhFVlliUyJ9.eyJuaWNrbmFtZSI6InNpcnI1MDUwIiwibmFtZSI6IlJhaHVsIiwicGljdHVyZSI6Imh0dHBzOi8vcy5ncmF2YXRhci5jb20vYXZhdGFyLzc5NzY5MjQ3Mjg3NzgwMjdjMTc1OGEwZWE5MDEwZTA4P3M9NDgwJnI9cGcmZD1odHRwcyUzQSUyRiUyRmNkbi5hdXRoMC5jb20lMkZhdmF0YXJzJTJGcmEucG5nIiwidXBkYXRlZF9hdCI6IjIwMjAtMDktMzBUMDk6NTI6MTYuMzY5WiIsImVtYWlsIjoic2lycjUwNTBAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsImlzcyI6Imh0dHBzOi8vaG9wZWZtLnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJhdXRoMHw1ZjRkZjExN2ZhMzY3YTAwNjgwYWZjZWYiLCJhdWQiOiJIQnF0QUJFTEZsME1Iazk5UWlFTXhYVnRXbldtNXI1NyIsImlhdCI6MTYwMTQ1OTUzNiwiZXhwIjoxNjA1MDU5NTM2fQ.H4lf39yuCBxM_yxlP8d_3jseZ27fbS3766RLr-LXGcGMNNBW2hSVZGmAm_1V4Uu4Nh5Id8AyyEC4wBTHLnzTZssf6RkLJUEMZtv3leUOsQV2sqD6NQ5LAtUnViRtvY9TJtZMfKcCfz8ApQlq7_8bOgGTbYjpfMBCosNU7-gN1r_NBH91InRxYw6g_OnoouECptEeZXwsU4jPFFgYYdqiRJJeCgiCoqT9Y2xb4T3Cm0L0mkgxi7aRv7jThFp9_OFlBiupb4cRCrmSIp_ipR7dYKZvOpcZ3GgjAG34CSwAhHZ-W2BPDa8ldI9iNs3pdo6KThJBHzcf3xJObPJ9a-xl7g

###
GET https://u84g6plpn8.execute-api.us-west-1.amazonaws.com/shows/category/1
Authorization: bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImI3MGxqUlo5ak5UWEIwWmhFVlliUyJ9.eyJuaWNrbmFtZSI6InNpcnI1MDUwIiwibmFtZSI6IlJhaHVsIiwicGljdHVyZSI6Imh0dHBzOi8vcy5ncmF2YXRhci5jb20vYXZhdGFyLzc5NzY5MjQ3Mjg3NzgwMjdjMTc1OGEwZWE5MDEwZTA4P3M9NDgwJnI9cGcmZD1odHRwcyUzQSUyRiUyRmNkbi5hdXRoMC5jb20lMkZhdmF0YXJzJTJGcmEucG5nIiwidXBkYXRlZF9hdCI6IjIwMjAtMDktMzBUMDk6NTI6MTYuMzY5WiIsImVtYWlsIjoic2lycjUwNTBAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsImlzcyI6Imh0dHBzOi8vaG9wZWZtLnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJhdXRoMHw1ZjRkZjExN2ZhMzY3YTAwNjgwYWZjZWYiLCJhdWQiOiJIQnF0QUJFTEZsME1Iazk5UWlFTXhYVnRXbldtNXI1NyIsImlhdCI6MTYwMTQ1OTUzNiwiZXhwIjoxNjA1MDU5NTM2fQ.H4lf39yuCBxM_yxlP8d_3jseZ27fbS3766RLr-LXGcGMNNBW2hSVZGmAm_1V4Uu4Nh5Id8AyyEC4wBTHLnzTZssf6RkLJUEMZtv3leUOsQV2sqD6NQ5LAtUnViRtvY9TJtZMfKcCfz8ApQlq7_8bOgGTbYjpfMBCosNU7-gN1r_NBH91InRxYw6g_OnoouECptEeZXwsU4jPFFgYYdqiRJJeCgiCoqT9Y2xb4T3Cm0L0mkgxi7aRv7jThFp9_OFlBiupb4cRCrmSIp_ipR7dYKZvOpcZ3GgjAG34CSwAhHZ-W2BPDa8ldI9iNs3pdo6KThJBHzcf3xJObPJ9a-xl7g
